name: Deploy to GCP

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          version: '355.0.0'
          project_id: cs-tmpl-test
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      
      - name: Install dependencies
        run: npm ci

      - name: Build static website
        run: npm run build

      - name: Deploy to GCP
        run: |
          gcloud app deploy --quiet
